sudo: false

language: rust
env:
  global:
    - RUST_BACKTRACE=1

arch:
  - arm64

os:
  - linux
  - osx

rust:
  - nightly
  - stable

script:
  - rustup component add rustfmt
  - rustup component add clippy
  - cargo fmt --all -- --check
  - cargo clippy --all-targets --all-features -- --deny warnings
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo bench --verbose --all
