name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    env:
      RUST_BACKTRACE: 1
    steps:
    - uses: actions/checkout@v2
    - name: Set up toolchains
      run: |
        rustup component add rustfmt
        rustup component add clippy
    - name: Check format
      run: cargo fmt --all -- --check
    - name: Lints
      run: cargo clippy --all-targets --all-features -- --deny warnings
    - name: Build
      run: cargo build --verbose --all
    - name: Run tests
      run: cargo test --verbose --all
    - name: Run benches
      run: cargo bench --verbose --all
